// The /latin page is generated by typing through the engine; these pin what it
// must keep finding, so a layout change that drops a letter fails here first.

import {describe, expect, test} from "bun:test";
import {latinLetters, coverage} from "../src/latin-data.ts";

const letters = latinLetters();
const keysOf = (g: string) => letters.find((l) => l.glyph === g)?.keys;

describe("latin letters", () => {
	test("single dead keys", () => {
		expect(keysOf("ł")).toBe("⌥y l");
		expect(keysOf("ș")).toBe("⌥, s");
		expect(keysOf("ő")).toBe("⌥⇧e o");
		expect(keysOf("İ")).toBe("⌥. ⇧I");
	});

	test("stacked marks and digraph letters", () => {
		expect(keysOf("ǘ")).toBeDefined();
		expect(keysOf("ệ")).toBeDefined();
		expect(keysOf("ß")).toBe("s⇧S");
		expect(keysOf("ǣ")).toBe("⌥a a⇧E");
	});

	test("every listed alphabet is fully typeable", () => {
		for (const c of coverage(letters)) expect({name: c.name, missing: c.missing}).toEqual({name: c.name, missing: []});
	});
});
