// Bakes content/*.md into src/content.gen.ts at build time.
//
// Why bake instead of reading at runtime: on a live Cloudflare Worker there is
// no filesystem, and the read-only ASSETS directory can't list entries. Baking
// keeps the .md files as the portable source of truth while compiling their text
// into the worker bundle — identical behavior in `wrangler dev` and on deploy.
// Runs via the `prebuild`/`predevelop` npm hooks, so it's always fresh.

import fm from "front-matter";
import {existsSync, readdirSync, readFileSync, writeFileSync} from "node:fs";
import {join} from "node:path";

const root = join(import.meta.dir, "..");
const contentDir = join(root, "content");
const out = join(root, "src", "content.gen.ts");

interface Doc {
	attributes: {title: string; description?: string};
	body: string;
}

interface Post {
	slug: string;
	attributes: {title: string; description?: string; date: string; draft?: boolean};
	body: string;
}

const docs: Record<string, Doc> = {};
for (const file of readdirSync(contentDir).sort()) {
	if (!file.endsWith(".md")) continue;
	const name = file.replace(/\.md$/, "");
	const {attributes, body} = fm(readFileSync(join(contentDir, file), "utf8")) as unknown as Doc;
	docs[name] = {attributes, body};
}

// Blog posts: content/blog/*.md, dated frontmatter, newest first. A post with
// `draft: true` bakes (so its URL renders for preview) but stays out of the
// index and the feed until the flag comes off.
const blogDir = join(contentDir, "blog");
const posts: Post[] = [];
if (existsSync(blogDir)) {
	for (const file of readdirSync(blogDir).sort()) {
		if (!file.endsWith(".md")) continue;
		const slug = file.replace(/\.md$/, "");
		const {attributes, body} = fm(readFileSync(join(blogDir, file), "utf8")) as unknown as Post;
		posts.push({slug, attributes, body});
	}
	posts.sort((a, b) => (a.attributes.date < b.attributes.date ? 1 : -1));
}

const next =
	`// GENERATED by scripts/bake-content.ts from content/*.md — do not edit.\n` +
	`export interface Doc {\n\tattributes: {title: string; description?: string};\n\tbody: string;\n}\n` +
	`export interface Post {\n\tslug: string;\n\tattributes: {title: string; description?: string; date: string; draft?: boolean};\n\tbody: string;\n}\n` +
	`export const docs: Record<string, Doc> = ${JSON.stringify(docs, null, "\t")};\n` +
	`export const posts: Post[] = ${JSON.stringify(posts, null, "\t")};\n`;

// Only write when the content changed — writing every build retriggers shovel's
// file watcher (content.gen.ts lives under src/), causing an infinite rebuild loop.
if (!existsSync(out) || readFileSync(out, "utf8") !== next) {
	writeFileSync(out, next);
	console.log(`baked ${Object.keys(docs).length} doc(s) + ${posts.length} post(s) → src/content.gen.ts`);
} else {
	console.log(`content unchanged (${Object.keys(docs).length} doc(s), ${posts.length} post(s))`);
}
