// Generated by cbindgen from engine/src/ffi.rs. Do not hand-edit —
// regenerate with `cbindgen --config cbindgen.toml -o include/ipabet_engine.h`
// from engine/ after changing the FFI surface.

#ifndef IPABET_ENGINE_H
#define IPABET_ENGINE_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define PENDING_MAX 16

#define EDIT_TEXT_MAX 64

/**
 * Never a real codepoint (always >= 0): the pending "raise" operator.
 */
#define PENDING_RAISE -1

/**
 * Never a real codepoint: the pending "lower" operator.
 */
#define PENDING_LOWER -2

typedef enum CEditType {
    Insert = 0,
    Replace = 1,
    Pass = 2,
    Noop = 3,
} CEditType;

typedef struct Engine Engine;

typedef struct CEdit {
    enum CEditType edit_type;
    /**
     * UTF-8, NUL-terminated. Truncated (never split mid-codepoint) if a
     * result somehow exceeded EDIT_TEXT_MAX — never happens in practice; a
     * base plus its stacked marks is at most a handful of codepoints.
     */
    char text[EDIT_TEXT_MAX];
    /**
     * Codepoints to remove from the end of text_before (Replace only).
     */
    int32_t replace_length;
} CEdit;

typedef struct CPending {
    int32_t items[PENDING_MAX];
    int32_t count;
} CPending;

typedef struct CStep {
    struct CEdit edit;
    struct CPending pending;
    bool chain_broken;
    bool has_chain_broken;
} CStep;

typedef struct CKeystroke {
    /**
     * NUL-terminated UTF-8 — "a", "5", ";", "Escape", "⌫" …
     */
    const char *key;
    bool shift;
    bool option;
    bool shift_broke;
    bool caps_lock;
    bool control;
} CKeystroke;

/**
 * # Safety
 * `spec_json` must be a valid NUL-terminated UTF-8 C string. Returns null on
 * a parse error — a build/packaging bug (a malformed spec.json shipped),
 * not a runtime condition the caller recovers from.
 */
 struct Engine *ipabet_engine_new(const char *spec_json);

/**
 * # Safety
 * `engine` must be a pointer previously returned by `ipabet_engine_new` and
 * not already freed.
 */
 void ipabet_engine_free(struct Engine *engine);

/**
 * # Safety
 * `engine` must be a live pointer from `ipabet_engine_new`.
 */
 void ipabet_engine_set_capital_digraphs(struct Engine *engine, bool on);

/**
 * # Safety
 * `engine` must be live; `locale` must be a valid NUL-terminated UTF-8 C string.
 */
 void ipabet_engine_set_quote_locale(struct Engine *engine, const char *locale);

/**
 * # Safety
 * `engine` must be live; `text_before` a valid NUL-terminated UTF-8 C string;
 * `keystroke.key` a valid NUL-terminated UTF-8 C string.
 */

struct CStep ipabet_engine_handle_key(const struct Engine *engine,
                                      const char *text_before,
                                      struct CKeystroke keystroke,
                                      struct CPending pending,
                                      bool chain_broken);

/**
 * # Safety
 * `engine` must be live; `text_before` a valid NUL-terminated UTF-8 C string.
 */

struct CStep ipabet_engine_handle_backspace(const struct Engine *engine,
                                            const char *text_before,
                                            struct CPending pending);

/**
 * # Safety
 * `engine` must be live; `text_before` a valid NUL-terminated UTF-8 C string.
 */

struct CStep ipabet_engine_handle_unconvert(const struct Engine *engine,
                                            const char *text_before,
                                            struct CPending pending);

/**
 * # Safety
 * `engine` must be live. `out` must point to at least `out_cap` bytes.
 */

void ipabet_preview_string(const struct Engine *engine,
                           struct CPending pending,
                           char *out,
                           uintptr_t out_cap);

/**
 * # Safety
 * `engine` must be live. `out` must point to at least `out_cap` bytes.
 */

void ipabet_commit_string(const struct Engine *engine,
                          struct CPending pending,
                          char *out,
                          uintptr_t out_cap);

/**
 * # Safety
 * `keystroke.key` must be a valid NUL-terminated UTF-8 C string. `out` must
 * point to at least `out_cap` bytes.
 */
 void ipabet_native_char(struct CKeystroke keystroke, char *out, uintptr_t out_cap);

/**
 * # Safety
 * `text_before` and `native` must be valid NUL-terminated UTF-8 C strings.
 * `out` must point to at least `out_cap` bytes.
 */

void ipabet_apply_edit(const char *text_before,
                       const struct CEdit *edit,
                       const char *native,
                       char *out,
                       uintptr_t out_cap);

/**
 * # Safety
 * `text_before` must be a valid NUL-terminated UTF-8 C string.
 */
 uintptr_t ipabet_last_cluster_byte_len(const char *text_before);

#endif  /* IPABET_ENGINE_H */
