// Unicode names for every glyph IPAbet produces — presentation data for the
// /keys and /chart-adjacent pages, owned by the site (the engine never needs a
// glyph's name). Keyed by codepoint hex, space-joined for multi-cp glyphs,
// exactly as `nameKey` builds it. Moved verbatim out of spec/ipabet.xml.

export const GLYPH_NAMES: Record<string, string> = {
  "0268": "LATIN SMALL LETTER I WITH STROKE",
  "0294": "LATIN LETTER GLOTTAL STOP",
  "0295": "LATIN LETTER PHARYNGEAL VOICED FRICATIVE",
  "027e": "LATIN SMALL LETTER R WITH FISHHOOK",
  "0259": "LATIN SMALL LETTER SCHWA",
  "0251": "LATIN SMALL LETTER ALPHA",
  "0127": "LATIN SMALL LETTER H WITH STROKE",
  "0061": "LATIN SMALL LETTER A",
  "0062": "LATIN SMALL LETTER B",
  "0063": "LATIN SMALL LETTER C",
  "0064": "LATIN SMALL LETTER D",
  "0065": "LATIN SMALL LETTER E",
  "0066": "LATIN SMALL LETTER F",
  "0067": "LATIN SMALL LETTER G",
  "0068": "LATIN SMALL LETTER H",
  "0069": "LATIN SMALL LETTER I",
  "006a": "LATIN SMALL LETTER J",
  "006b": "LATIN SMALL LETTER K",
  "006c": "LATIN SMALL LETTER L",
  "006d": "LATIN SMALL LETTER M",
  "006e": "LATIN SMALL LETTER N",
  "006f": "LATIN SMALL LETTER O",
  "0070": "LATIN SMALL LETTER P",
  "0071": "LATIN SMALL LETTER Q",
  "0072": "LATIN SMALL LETTER R",
  "0073": "LATIN SMALL LETTER S",
  "0074": "LATIN SMALL LETTER T",
  "0075": "LATIN SMALL LETTER U",
  "0076": "LATIN SMALL LETTER V",
  "0077": "LATIN SMALL LETTER W",
  "0078": "LATIN SMALL LETTER X",
  "0079": "LATIN SMALL LETTER Y",
  "007a": "LATIN SMALL LETTER Z",
  "0258": "LATIN SMALL LETTER REVERSED E",
  "0289": "LATIN SMALL LETTER U BAR",
  "02a1": "LATIN LETTER GLOTTAL STOP WITH STROKE",
  "02a2": "LATIN LETTER REVERSED GLOTTAL STOP WITH STROKE",
  "027a": "LATIN SMALL LETTER TURNED R WITH LONG LEG",
  "027d": "LATIN SMALL LETTER R WITH TAIL",
  "2c71": "LATIN SMALL LETTER V WITH RIGHT HOOK",
  "025c": "LATIN SMALL LETTER REVERSED OPEN E",
  "025e": "LATIN SMALL LETTER CLOSED REVERSED OPEN E",
  "029c": "LATIN LETTER SMALL CAPITAL H",
  "00e6": "LATIN SMALL LETTER AE",
  "028c": "LATIN SMALL LETTER TURNED V",
  "0250": "LATIN SMALL LETTER TURNED A",
  "0276": "LATIN LETTER SMALL CAPITAL OE",
  "00e4": "LATIN SMALL LETTER A WITH DIAERESIS",
  "0253": "LATIN SMALL LETTER B WITH HOOK",
  "03b2": "GREEK SMALL LETTER BETA",
  "00e7": "LATIN SMALL LETTER C WITH CEDILLA",
  "0257": "LATIN SMALL LETTER D WITH HOOK",
  "00f0": "LATIN SMALL LETTER ETH",
  "025f": "LATIN SMALL LETTER DOTLESS J WITH STROKE",
  "0256": "LATIN SMALL LETTER D WITH TAIL",
  "025b": "LATIN SMALL LETTER OPEN E",
  "00f8": "LATIN SMALL LETTER O WITH STROKE",
  "0260": "LATIN SMALL LETTER G WITH HOOK",
  "0263": "LATIN SMALL LETTER GAMMA",
  "029d": "LATIN SMALL LETTER J WITH CROSSED-TAIL",
  "0262": "LATIN LETTER SMALL CAPITAL G",
  "0261": "LATIN SMALL LETTER SCRIPT G (the chart's single-story ɡ, exact codepoint)",
  "0266": "LATIN SMALL LETTER H WITH HOOK",
  "026a": "LATIN LETTER SMALL CAPITAL I",
  "0284": "LATIN SMALL LETTER DOTLESS J WITH STROKE AND HOOK",
  "029f": "LATIN LETTER SMALL CAPITAL L",
  "028e": "LATIN SMALL LETTER TURNED Y",
  "026d": "LATIN SMALL LETTER L WITH RETROFLEX HOOK",
  "0271": "LATIN SMALL LETTER M WITH HOOK",
  "014b": "LATIN SMALL LETTER ENG",
  "0272": "LATIN SMALL LETTER N WITH LEFT HOOK",
  "0274": "LATIN LETTER SMALL CAPITAL N",
  "0273": "LATIN SMALL LETTER N WITH RETROFLEX HOOK",
  "0252": "LATIN SMALL LETTER TURNED ALPHA",
  "0153": "LATIN SMALL LIGATURE OE",
  "0254": "LATIN SMALL LETTER OPEN O",
  "0275": "LATIN SMALL LETTER BARRED O",
  "0264": "LATIN SMALL LETTER RAMS HORN",
  "0278": "LATIN SMALL LETTER PHI",
  "03c7": "GREEK SMALL LETTER CHI",
  "0267": "LATIN SMALL LETTER HENG WITH HOOK",
  "0299": "LATIN LETTER SMALL CAPITAL B",
  "0280": "LATIN LETTER SMALL CAPITAL R",
  "0279": "LATIN SMALL LETTER TURNED R",
  "0281": "LATIN LETTER SMALL CAPITAL INVERTED R",
  "027b": "LATIN SMALL LETTER TURNED R WITH HOOK",
  "0283": "LATIN SMALL LETTER ESH",
  "0255": "LATIN SMALL LETTER C WITH CURL",
  "026c": "LATIN SMALL LETTER L WITH BELT",
  "0282": "LATIN SMALL LETTER S WITH HOOK",
  "03b8": "GREEK SMALL LETTER THETA",
  "0288": "LATIN SMALL LETTER T WITH RETROFLEX HOOK",
  "028a": "LATIN SMALL LETTER UPSILON",
  "026f": "LATIN SMALL LETTER TURNED M",
  "028b": "LATIN SMALL LETTER V WITH HOOK",
  "028d": "LATIN SMALL LETTER TURNED W",
  "0265": "LATIN SMALL LETTER TURNED H",
  "0270": "LATIN SMALL LETTER TURNED M WITH LONG LEG",
  "028f": "LATIN LETTER SMALL CAPITAL Y",
  "0292": "LATIN SMALL LETTER EZH",
  "0291": "LATIN SMALL LETTER Z WITH CURL",
  "026e": "LATIN SMALL LETTER LEZH",
  "0290": "LATIN SMALL LETTER Z WITH RETROFLEX HOOK",
  "0298": "LATIN LETTER BILABIAL CLICK",
  "01c0": "LATIN LETTER DENTAL CLICK",
  "01c3": "LATIN LETTER RETROFLEX CLICK",
  "01c2": "LATIN LETTER ALVEOLAR CLICK",
  "01c1": "LATIN LETTER LATERAL CLICK",
  "029b": "LATIN LETTER SMALL CAPITAL G WITH HOOK",
  "00df": "LATIN SMALL LETTER SHARP S",
  "026b": "LATIN SMALL LETTER L WITH MIDDLE TILDE",
  "00fe": "LATIN SMALL LETTER THORN (Icelandic)",
  "0131": "LATIN SMALL LETTER DOTLESS I (Turkish, Azeri, Kazakh)",
  "0199": "LATIN SMALL LETTER K WITH HOOK (Hausa)",
  "01b4": "LATIN SMALL LETTER Y WITH HOOK (Fula)",
  "0192": "LATIN SMALL LETTER F WITH HOOK (Ewe)",
  "0301": "COMBINING ACUTE ACCENT",
  "0300": "COMBINING GRAVE ACCENT",
  "0302": "COMBINING CIRCUMFLEX ACCENT",
  "030c": "COMBINING CARON",
  "0304": "COMBINING MACRON",
  "0303": "COMBINING TILDE (nasalized; press again: ͊ denasal → ͋ nasal escape → ͌ velopharyngeal friction — the nasal-port dimension)",
  "0308": "COMBINING DIAERESIS",
  "0306": "COMBINING BREVE (extra-short; ⇧ → ̮ breve below — DIN Arabic ḫ)",
  "030a": "COMBINING RING ABOVE",
  "0327": "COMBINING CEDILLA (⇧ → ̡ palatalized hook — the cedilla's sibling curl; the palatal hook on the palatal letter, Slavicist t̡ d̡)",
  "0326": "COMBINING COMMA BELOW",
  "0328": "COMBINING OGONEK (the Polish nasal hook; ⇧ → ̐ candrabindu, Indic nasalization — the nasal tenants on the nasal letter)",
  "032a": "COMBINING BRIDGE BELOW",
  "033a": "COMBINING INVERTED BRIDGE BELOW",
  "0320": "COMBINING MINUS SIGN BELOW",
  "0335": "COMBINING SHORT STROKE OVERLAY (⇧ → ̴ tilde overlay, velarized-or-pharyngealized; ¥ — y is the world's best-known stroked letter — is a memory hook, not a claim)",
  "031e": "COMBINING DOWN TACK BELOW",
  "031c": "COMBINING LEFT HALF RING BELOW (less rounded; press again: ͍ labial spreading — the un-rounding ladder. ⇧ → ̹ more rounded; press again: ͎ whistled — rounding taken to its endpoint)",
  "0329": "COMBINING VERTICAL LINE BELOW",
  "0349": "COMBINING LEFT ANGLE BELOW (weak articulation; ⇧ → ͈ strong/fortis, the Korean tense mark — F for force)",
  "033c": "COMBINING SEAGULL BELOW (linguolabial — tongue to lips; ⇧ → ‖ the major intonation-group double bar, its single-bar partner | the native ⇧\\ key)",
  "0361": "COMBINING DOUBLE INVERTED BREVE",
  "033d": "COMBINING X ABOVE",
  "02c8": "MODIFIER LETTER VERTICAL LINE",
  "02d0": "MODIFIER LETTER TRIANGULAR COLON",
  "02bb": "MODIFIER LETTER TURNED COMMA (ʻokina — Hawaiian, Uzbek oʻ; ⇧ → ʼ ejective. Opening form unshifted, as on every quote key)",
  "02de": "MODIFIER LETTER RHOTIC HOOK",
  "2198": "SOUTH EAST ARROW",
  "2193": "DOWNWARDS ARROW (ingressive airflow, extIPA; ⇧ → ↑ egressive — the digits' arrow run: step 6, contour 7, airflow 8)",
  "a71c": "MODIFIER LETTER RAISED DOWN ARROW",
  "02e9": "MODIFIER LETTER EXTRA-LOW TONE BAR",
  "02e8": "MODIFIER LETTER LOW TONE BAR",
  "02e7": "MODIFIER LETTER MID TONE BAR",
  "02e6": "MODIFIER LETTER HIGH TONE BAR (⇧ → ͇ alveolar, extIPA — the alveolar mark on the alveolar-tap digit)",
  "02e5": "MODIFIER LETTER EXTRA-HIGH TONE BAR",
  "031a": "COMBINING LEFT ANGLE ABOVE (no audible release; ⇧ → ͢ the sliding-articulation tie, extIPA)",
  "0319": "COMBINING RIGHT TACK BELOW",
  "0307": "COMBINING DOT ABOVE (pressed again on its own pending dot it commits · — the interpunct, Catalan's punt volat: l ⌥. ⌥. l → l·l)",
  "0309": "COMBINING HOOK ABOVE (hỏi)",
  "208d": "SUBSCRIPT LEFT PARENTHESIS (pre-voicing; ⇧ → ₎ post-voicing)",
  "02b9": "MODIFIER LETTER PRIME (Cyrillic romanization's soft sign — Gorʹkij; ⇧ → ʺ double prime, the hard sign)",
  "27e8": "MATHEMATICAL LEFT ANGLE BRACKET (the grapheme brackets — /phoneme/ [phone] ⟨grapheme⟩; opening unshifted, per the quote law. « » are the French locale's primary quotes)",
  "032f": "COMBINING INVERTED BREVE BELOW (non-syllabic — the diphthong glide, a vowel mark on the vowel key; ⇧ → ̑ the Slavic long-falling accent)",
};

const nameKey = (g: string) =>
  [...g].map((c) => c.codePointAt(0)!.toString(16).padStart(4, "0")).join(" ");

/** The Unicode name of a glyph, or "" if unlisted. */
export const nameOf = (glyph: string): string => GLYPH_NAMES[nameKey(glyph)] ?? "";
