// genkeylayout.swift — generates IPAbet.keylayout, a COSMETIC keyboard layout
// whose only job is to make the on-screen Keyboard Viewer show IPAbet's base
// layer. The real transformation engine decodes keys via USLayout (UCKeyTranslate
// against com.apple.keylayout.US) and never reads this layout's output, so this
// file is display-only and safe: a bad/absent layout just costs the preview.
//
// It mirrors US for every modifier layer (so the Option-Shift passthrough and
// capitals still type US characters if the OS ever forwards them), then paints
// the IPA bare glyphs onto the number row (base layer) and the two click
// letters onto Shift+1 / Shift+backslash.
//
// Usage: swift genkeylayout.swift > IPAbet.keylayout

import Carbon

let uchr: Data = {
    let filter = [kTISPropertyInputSourceID as String: "com.apple.keylayout.US"] as CFDictionary
    let cf = TISCreateInputSourceList(filter, true)!.takeRetainedValue()
    let src = (cf as! [TISInputSource]).first!
    let ptr = TISGetInputSourceProperty(src, kTISPropertyUnicodeKeyLayoutData)!
    return Unmanaged<CFData>.fromOpaque(ptr).takeUnretainedValue() as Data
}()

func us(_ keyCode: UInt16, _ mod: UInt32) -> String {
    uchr.withUnsafeBytes { raw in
        let layout = raw.baseAddress!.assumingMemoryBound(to: UCKeyboardLayout.self)
        var dead: UInt32 = 0, buf = [UniChar](repeating: 0, count: 8), len = 0
        UCKeyTranslate(layout, keyCode, UInt16(kUCKeyActionDown), mod,
                       UInt32(LMGetKbdType()), OptionBits(kUCKeyTranslateNoDeadKeysBit),
                       &dead, buf.count, &len, &buf)
        return String(utf16CodeUnits: buf, count: len)
    }
}

let SHIFT = (UInt32(shiftKey)  >> 8) & 0xFF
let OPT   = (UInt32(optionKey) >> 8) & 0xFF

// keyMap index → the UCKeyTranslate modifier bits that layer mirrors.
let layerMod: [Int: UInt32] = [0: 0, 1: SHIFT, 2: OPT, 3: OPT | SHIFT]

// Cosmetic overrides: (keyMapIndex, keyCode) → scalar. Base-layer IPA glyphs
// (number row) plus the click letters on the Shift layer.
let overrides: [String: Unicode.Scalar] = [
    "0,18": "\u{0268}",  // 1 → ɨ
    "0,19": "\u{0294}",  // 2 → ʔ
    "0,20": "\u{0295}",  // 3 → ʕ
    "0,21": "\u{027E}",  // 4 → ɾ
    "0,23": "\u{0259}",  // 5 → ə
    "0,22": "\u{0250}",  // 6 → ɐ
    "0,26": "\u{0127}",  // 7 → ħ
    "1,18": "\u{01C3}",  // Shift+1 → ǃ (retroflex click)
    "1,42": "\u{01C0}",  // Shift+\ → ǀ (dental click)
]

func esc(_ s: String) -> String {
    guard let scalar = s.unicodeScalars.first else { return "" }
    let v = scalar.value
    if v == 0x09 || v == 0x0D { return String(format: "&#x%04X;", v) }  // tab, return (XML-legal)
    if v < 0x20 || v == 0x7F { return "" }      // other control keys (arrows, F-keys): no output
    if v == 0x26 { return "&#x0026;" }          // &
    if v == 0x3C { return "&#x003C;" }          // <
    if v == 0x3E { return "&#x003E;" }          // >
    if v == 0x22 { return "&#x0022;" }          // "
    if v > 0x7E { return String(format: "&#x%04X;", v) }
    return String(UnicodeScalar(v)!)
}

var out = """
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE keyboard SYSTEM "file://localhost/System/Library/DTDs/KeyboardLayout.dtd">
<!-- Generated by tools/genkeylayout.swift — cosmetic Keyboard Viewer layout for IPAKey. -->
<keyboard group="126" id="-31201" name="IPAbet" maxout="1">
  <layouts>
    <layout first="0" last="17" mapSet="ipabet" modifiers="mods"/>
  </layouts>
  <modifierMap id="mods" defaultIndex="0">
    <keyMapSelect mapIndex="0"><modifier keys="anyControl? command?"/></keyMapSelect>
    <keyMapSelect mapIndex="1"><modifier keys="anyShift caps? anyControl? command?"/><modifier keys="caps anyControl? command?"/></keyMapSelect>
    <keyMapSelect mapIndex="2"><modifier keys="anyOption caps? anyControl? command?"/></keyMapSelect>
    <keyMapSelect mapIndex="3"><modifier keys="anyShift anyOption caps? anyControl? command?"/></keyMapSelect>
  </modifierMap>
  <keyMapSet id="ipabet">

"""

for index in 0...3 {
    out += "    <keyMap index=\"\(index)\">\n"
    for kc in UInt16(0)...127 {
        let output: String
        if let ov = overrides["\(index),\(kc)"] {
            output = esc(String(ov))
        } else {
            output = esc(us(kc, layerMod[index]!))
        }
        out += "      <key code=\"\(kc)\" output=\"\(output)\"/>\n"
    }
    out += "    </keyMap>\n"
}

out += """
  </keyMapSet>
</keyboard>
"""

print(out)
